baseURL = 'https://glook137.github.io/'
languageCode = 'en-us'
title = 'GlooK blog'
theme = "PaperMod"
[params]
  [params.assets]
    favicon = "/image/favicon.ico"
    favicon16x16 = "/image/favicon-16x16.png"
    favicon32x32 = "/image/favicon-32x32.png"
    apple_touch_icon = "/image/apple-touch-icon.png"
    safari_pinned_tab = "/image/safari-pinned-tab.svg"
    theme_color = "#2e2e33"
    msapplication_TileColor = "#2e2e33"
